"""empty message

Revision ID: 1ec6365a9d50
Revises: 661da311a457
Create Date: 2019-10-10 10:13:09.792627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ec6365a9d50'
down_revision = '661da311a457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobmodel',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('salary_lower', sa.Integer(), nullable=True),
    sa.Column('salary_upper', sa.Integer(), nullable=True),
    sa.Column('experience_lower', sa.Integer(), nullable=True),
    sa.Column('experience_upper', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=16), nullable=True),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.Column('company', sa.String(length=32), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['dataanalysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobmodel_title'), 'jobmodel', ['title'], unique=True)
    op.drop_index('ix_lagou_name', table_name='lagou')
    op.drop_table('lagou')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lagou',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('analysis_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['dataanalysis.id'], name='lagou_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_lagou_name', 'lagou', ['name'], unique=True)
    op.drop_index(op.f('ix_jobmodel_title'), table_name='jobmodel')
    op.drop_table('jobmodel')
    # ### end Alembic commands ###
