"""empty message

Revision ID: 661da311a457
Revises: 
Create Date: 2019-10-09 17:36:02.717204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661da311a457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataanalysis',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataanalysis_name'), 'dataanalysis', ['name'], unique=True)
    op.create_table('lagou',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['dataanalysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lagou_name'), 'lagou', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lagou_name'), table_name='lagou')
    op.drop_table('lagou')
    op.drop_index(op.f('ix_dataanalysis_name'), table_name='dataanalysis')
    op.drop_table('dataanalysis')
    # ### end Alembic commands ###
