"""empty message

Revision ID: c0c4df10464a
Revises: 
Create Date: 2019-10-14 20:52:14.164042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c4df10464a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysislistmodel',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['dataanalysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysislistmodel_code'), 'analysislistmodel', ['code'], unique=True)
    op.create_index(op.f('ix_analysislistmodel_name'), 'analysislistmodel', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysislistmodel_name'), table_name='analysislistmodel')
    op.drop_index(op.f('ix_analysislistmodel_code'), table_name='analysislistmodel')
    op.drop_table('analysislistmodel')
    # ### end Alembic commands ###
